# Simulations

In order to exemplify the utility of this package, a handful of hypothetical
data will be presented, together with a proposal of an appropriate likelihood
function that is expected to segment the data in an expected manner.

## Correlated random variables

Let $C_1$, $C_2$, ..., $C_n$ a sequence of $n$ sets of data points, each with $m$
observations represented by $C_k = \{c_{k1},\ c_{k2},\ ...,\ c_{km}\}$, with
$1 \le k \le n$. Assume that each $C_k$ is a function of an unknown set of independent
random variables $X$, such that $C_k = f_k(X)$. When used together with a multivariate
likelihood [@multivariate-likelihood], it's possible to identify the set of $N_b$ changepoints
$b_1, ..., b_{N_b}$, with $b_0 = 1$ and $b_{N_b + 1} = n + 1$, such that all $f_k$, for
$b_i \le k \le b_{i+1}-1$ is a function of the same set of independent random variables $X$,
for each $1 \le i \le N_b$.

### Example of correlated random variables

Let $X_1, ..., X_6$ be independent random variables and $C_1, ..., C_{15}$ be
defined as in @\ref(eq:example-columns). It's possible to see the first segment $C_1, ..., C_5$
depend on $X_1, X_2$, the second segment $C_6, ..., C_{10}$ depend on $X_3, X_4$ and the third
and last segment $C_{11}, ..., C_{15}$ depend on $X_4, X_5$. Therefore, the changepoints would
be $b_1 = 6$ and $b_2 = 11$. In order to exemplify that, 

$$
\begin{align}
C_1 & = X_1 \\
C_2 & = X_1 - X_2 \\
C_3 & = X_2 \\
C_4 & = X_1 + X_2 \\
C_5 & = X_1 \\
C_6 & = X_3 \\
C_7 & = X_3 - X_4 \\
C_8 & = X_4 \\
C_9 & = X_3 + X_4 \\
C_{10} & = X_3 \\
C_{11} & = X_5 \\
C_{12} & = X_5 - X_6 \\
C_{13} & = X_6 \\
C_{14} & = X_5 + X_6 \\
C_{15} & = X_5
\end{align}
(\#eq:example-columns)
$$

Considering the equations above, it's possible 

Also, let $Eq_1$, $Eq_2$, ..., $Eq_N$ be $N$ equations which specify
relationships between the points arbitrary random variables. Therefore, build
the data matrix $D$ with each set of observations $X_k$ in each column.

$$
D = [x_{ij}], 1 \le i \le m \text{ and } 1 \le j \le n
(\#eq:multivariatedata)
$$

Let $C(D)$ be the set of changepoints that split \@ref(eq:multivariatedata) in
changepoints with maximum likelihood. If the maximum likelihood of a discrete
multivariate distribution is used, the set of changepoints in the data will be
defined by the $Eq_k$, with $1 \le k \le N$, for which there are no common
random variables relationships defined in each sequence of continuous equations
relationships. In other words, $C(D)$ will be the points that split $D$ in
segments of random variables independent of each other.

To ilustrate, assume there are $n = 15$ sequences of random variables observations, with 

```{r}
# R code building the data
```

So, we use `segmentr` in order to find the expected segment points.

