# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call('_segmentr_rcpp_hello', PACKAGE = 'segmentr')
}

multivariate <- function(x) {
    .Call('_segmentr_multivariate', PACKAGE = 'segmentr', x)
}

segment_base <- function(x, loglikmethod, r_loglikfun) {
    .Call('_segmentr_segment_base', PACKAGE = 'segmentr', x, loglikmethod, r_loglikfun)
}

